
import type { MeetingRoom } from './types';

export const MEETING_ROOMS: MeetingRoom[] = [
  {
    id: 17,
    name: 'Auditorium Jawadwipa 1',
    floor: '1st Floor',
    capacity: 35,
    address: 'Injourney Airport Center',
    facilities: ['TV', 'AC', 'Proyektor', 'Sound System'],
    image: '/images/meeting-rooms/r4.jpeg',
  },
  {
    id: 18,
    name: 'Auditorium Jawadwipa 2',
    floor: '1st Floor',
    capacity: 35,
    address: 'Injourney Airport Center',
    facilities: ['TV', 'AC', 'Proyektor', 'Sound System'],
    image: '/images/meeting-rooms/r5.jpeg',
  },
  {
    id: 15,
    name: 'Balidwipa Meeting Room',
    floor: '2nd Floor',
    capacity: 20,
    address: 'Injourney Airport Center',
    facilities: ['TV', 'AC', 'Proyektor'],
    image: '/images/meeting-rooms/r9.jpeg',
  },
  {
    id: 5,
    name: 'Borobudur Conference Hall',
    floor: '3rd Floor',
    capacity: 30,
    address: 'Injourney Airport Center',
    facilities: ['TV', 'AC', 'Proyektor'],
    image: '/images/meeting-rooms/r11.jpeg',
  },
  {
    id: 11,
    name: 'Cedaya Meeting Room',
    floor: '1st Floor',
    capacity: 15,
    address: 'Injourney Airport Center',
    facilities: ['TV', 'AC', 'Proyektor'],
    image: '/images/meeting-rooms/r7.jpeg',
  },
  {
    id: 12,
    name: 'Celebes Meeting Room',
    floor: '1st Floor',
    capacity: 15,
    address: 'Injourney Airport Center',
    facilities: ['TV', 'AC', 'Proyektor'],
    image: '/images/meeting-rooms/r8.jpeg',
  },
  {
    id: 3,
    name: 'Garuda Discussion Room',
    floor: '2nd Floor',
    capacity: 6,
    address: 'Injourney Airport Center',
    facilities: ['TV', 'AC', 'Proyektor'],
    image: '/images/meeting-rooms/r3.jpeg',
  },
  {
    id: 13,
    name: 'Kalamanthana Meeting Room',
    floor: '1st Floor',
    capacity: 15,
    address: 'Injourney Airport Center',
    facilities: ['TV', 'AC', 'Proyektor', 'Whiteboard'],
    image: '/images/meeting-rooms/r6.jpeg',
  },
  {
    id: 4,
    name: 'Komodo Meeting Room',
    floor: '1st Floor',
    capacity: 8,
    address: 'Injourney Airport Center',
    facilities: ['TV', 'AC'],
    image: '/images/meeting-rooms/r12.jpeg',
  },
  {
    id: 14,
    name: 'Nusanipa Meeting Room',
    floor: '1st Floor',
    capacity: 15,
    address: 'Injourney Airport Center',
    facilities: ['TV', 'AC'],
    image: '/images/meeting-rooms/r2.jpeg',
  },
  {
    id: 2,
    name: 'Nusantara Conference Room',
    floor: '2nd Floor',
    capacity: 20,
    address: 'Injourney Airport Center',
    facilities: ['TV', 'AC', 'Proyektor'],
    image: '/images/meeting-rooms/r13.jpeg',
  },
  {
    id: 1,
    name: 'Samudrantha Meeting Room',
    floor: '1st Floor',
    capacity: 10,
    address: 'Injourney Airport Center',
    facilities: ['TV', 'AC', 'Proyektor'],
    image: '/images/meeting-rooms/r1.jpeg',
  },
  {
    id: 16,
    name: 'Swarnadwipa Meeting Room',
    floor: '2nd Floor',
    capacity: 25,
    address: 'Injourney Airport Center',
    facilities: ['TV', 'AC', 'Proyektor'],
    image: '/images/meeting-rooms/r10.jpeg',
  },
];
